- menu_name: "Dienste"

- name: "Kontakt"
  url: "/kontakt/"
  title: "Kontakt"

- name: "RSS"
  url: "/feed.xml"
  title: "Abboniere RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Abboniere Atom Feed"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
